Task 3
vladyoslav/formal-lang-course pull request #3
Opened 2023-09-27 10:52 UTC by vladyoslav

2023-09-27 13:01 UTC, EgorOrachyov requested changes
Суффикс _lib в именах файлов излишний, лучше убрать

2023-09-27 13:01 UTC, EgorOrachyov commented on project/rpq_lib.py
> +import project.automata_lib as al
сокращение до 2х букв для networkx еще приемлемы, но остальное уже чересчур

2023-09-27 13:01 UTC, EgorOrachyov commented on project/rpq_lib.py
> +def regular_path_query(
тут не хватает уточнения о каком алгоритме речь, `rpq_(what? reuqlar, kron based, tensor, etc)`

2023-09-27 13:01 UTC, EgorOrachyov commented on project/rpq_lib.py
> +    result = []
тут внимательнее, может set требуется, если дубликаты будут

2023-09-27 14:21 UTC, vladyoslav commented on project/rpq_lib.py
> +import project.automata_lib as al
Исправил

2023-09-27 14:22 UTC, vladyoslav commented on project/rpq_lib.py
> +def regular_path_query(
Переименовал функцию и файл

2023-09-27 14:22 UTC, vladyoslav commented on project/rpq_lib.py
> +    result = []
Сделал

2023-09-28 09:51 UTC, EgorOrachyov approved these changes

2023-09-28 10:43 UTC, merged